# Generated by Django 4.2.16 on 2024-10-08 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, unique=True)),
                ('answer', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(0, 'General Knowledge'), (1, 'Sport'), (2, 'History'), (3, 'Science & Nature'), (4, 'Music & Media'), (5, 'Past adventure')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_stamps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
